# fly.toml app configuration file generated for muddy-river-556 on 2023-10-26T16:02:44+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-river-556"
primary_region = "sin"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
